### ISSUE TITLE
Worker crashes while using pull when stats page is opened

### ISSUE THREAD

**Issue by Goz3rr** [sergey-dryabzhinsky/nginx-rtmp-module#66]
I have my nginx 1.9.10 compiled with the following arguments:

```
--prefix=/usr/local/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --user=www-data --group=www-data --http-client-body-temp-path=/var/tmp/nginx/client/ --http-proxy-temp-path=/var/tmp/nginx/proxy/ --http-fastcgi-temp-path=/var/tmp/nginx/fcgi/ --with-ipv6 --without-http_uwsgi_module --without-http_scgi_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_xslt_module --with-http_realip_module --add-module=modules/headers-more-nginx-module --add-module=modules/nginx-rtmp-module
```

And the following config:
```nginx
worker_processes 1;
worker_rlimit_nofile 16384;

pid        /var/run/nginx.pid;
error_log  /var/log/nginx/error.log debug;

events {
    worker_connections 8192;
    use                epoll;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    variables_hash_max_size       1024;
    map_hash_max_size             2048;
    server_names_hash_bucket_size 128;
    types_hash_max_size           1024;

    access_log /var/log/nginx/access.log;
    charset UTF-8;

    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            off;
    server_tokens          off;
    underscores_in_headers on;

    sendfile_max_chunk          1m;
    keepalive_timeout           30;
    client_max_body_size        32m;
    client_body_buffer_size     1m;
    client_body_timeout         10;
    client_header_timeout       10;
    large_client_header_buffers 4 16k;
    send_timeout                10;
    reset_timedout_connection   on;

    open_file_cache          max=2048 inactive=10s;
    open_file_cache_valid    30s;
    open_file_cache_min_uses 4;
    open_file_cache_errors   on;

    gzip              on;
    gzip_vary         on;
    gzip_disable      "MSIE [1-6]\.(?!.*SV1)";
    gzip_proxied      expired no-cache no-store private auth;
    gzip_http_version 1.1;
    gzip_comp_level   3;
    gzip_min_length   256;
    gzip_buffers      16 8k;
    gzip_types        text/plain text/css text/xml
                      application/javascript application/json
                      application/xhtml+xml application/xml+rss;

    fastcgi_buffering off;

    ssl_session_cache         shared:SSL:20m;
    ssl_session_timeout       10m;
    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
    ssl_buffer_size           8k;
    ssl_dhparam               /etc/nginx/dhparam.pem;

    add_header "X-Served-By" "faraday";

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;

        ssl_certificate     /usr/local/nginx/cert/default.crt;
        ssl_certificate_key /usr/local/nginx/cert/default.key;

        error_page 404 /404.html;

        #location / {
        #    access_log off;
        #    return 404;
        #}

        location = /404.html {
            root /usr/local/nginx/html/;
            log_not_found off;
            access_log off;
        }
    }

    server {
        listen 80;
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/faraday.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/faraday.domain.com/privkey.pem;

        server_name faraday.domain.com;
    }

    server {
        listen 80;
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/faraday.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/faraday.domain.com/privkey.pem;

        server_name rtmp.domain.com live.domain.com;

        location /dash {
            root /tmp;

            more_set_headers "Cache-Control: no-cache";
            more_set_headers "Access-Control-Allow-Origin: *";

            types {
                video/mp4    m4v;
                audio/mp4    m4a;
            }
        }
    }

    server {
        listen 8080;

        location /nginx_status {
            stub_status on;
            access_log  off;
        }

        location /rtmp_status {
            rtmp_stat all;
            rtmp_stat_stylesheet rtmp_status.xsl;
        }

        location /rtmp_status.xml {
            rtmp_stat all;
        }

        location /rtmp_status.json {
            proxy_pass http://127.0.0.1:8080/rtmp_status.xml;
            xslt_types "*";
            xslt_stylesheet /usr/local/nginx/html/rtmp_status_json.xsl;
            more_set_headers 'Content-Type: application/json';
        }

        location /rtmp_status.xsl {
            root /usr/local/nginx/html;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application stream {
            live on;
            record off;

            pull rtmp://stream.domain.com:1935/stream;

            dash on;
            dash_path /tmp/dash;
            dash_fragment 2s;
            dash_playlist_length 10s;


            allow play all;
            allow publish all;
        }
    }
}
```

Streaming to the other server and having it pulled dynamically on this server works fine, until a request to `/rtmp_status` is made on the pulling server, then the following happens:

```
2016/01/28 23:29:13 [notice] 2665#0: using the "epoll" event method
2016/01/28 23:29:13 [notice] 2665#0: nginx/1.9.10
2016/01/28 23:29:13 [notice] 2665#0: built by gcc 4.9.2 (Debian 4.9.2-10)
2016/01/28 23:29:13 [notice] 2665#0: OS: Linux 3.16.0-4-amd64
2016/01/28 23:29:13 [notice] 2665#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2016/01/28 23:29:13 [notice] 2666#0: start worker processes
2016/01/28 23:29:13 [notice] 2666#0: start worker process 2667
2016/01/28 23:29:13 [notice] 2666#0: start cache manager process 2668
2016/01/28 23:29:31 [info] 2667#0: *2 client connected 'xxx.xxx.xxx.xxx'
2016/01/28 23:29:31 [info] 2667#0: *2 connect: app='stream' args='' flashver='WIN 20,0,0,286' swf_url='https://stream.domain.com/jwplayer-7.2.4/jwplayer.flash.swf' tc_url='rtmp://live.domain.com/stream/' page_url='https://stream.domain.com/teststream' acodecs=3575 vcodecs=252 object_encoding=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:32 [info] 2667#0: *2 createStream, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:32 [info] 2667#0: *2 play: name='teststream' args='' start=0 duration=0 reset=0 silent=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:32 [debug] 2667#0: *2 log: ngx_rtmp_log_play
2016/01/28 23:29:32 [debug] 2667#0: *2 log: ngx_rtmp_log_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 notify: ngx_rtmp_notify_play
2016/01/28 23:29:32 [debug] 2667#0: *2 notify: ngx_rtmp_notify_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 exec: ngx_rtmp_exec_play
2016/01/28 23:29:32 [debug] 2667#0: *2 exec: ngx_rtmp_exec_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 relay: ngx_rtmp_relay_play
2016/01/28 23:29:32 [info] 2667#0: *2 relay: create pull name='teststream' app='' playpath='' url='stream.domain.com:1935/stream', client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:32 [debug] 2667#0: *2 relay: ngx_rtmp_relay_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 play: ngx_rtmp_play_play
2016/01/28 23:29:32 [debug] 2667#0: *2 play: ngx_rtmp_play_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 live: ngx_rtmp_live_play
2016/01/28 23:29:32 [debug] 2667#0: *2 live: ngx_rtmp_live_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 access: ngx_rtmp_access_play
2016/01/28 23:29:32 [debug] 2667#0: *2 access: ngx_rtmp_access_play: next
2016/01/28 23:29:32 [debug] 2667#0: *2 cmd: ngx_rtmp_cmd_play
2016/01/28 23:29:42 [notice] 2666#0: signal 17 (SIGCHLD) received
2016/01/28 23:29:42 [alert] 2666#0: worker process 2667 exited on signal 11
2016/01/28 23:29:42 [notice] 2666#0: start worker process 2673
2016/01/28 23:29:42 [notice] 2666#0: signal 29 (SIGIO) received
2016/01/28 23:29:50 [info] 2673#0: *5 client connected 'xxx.xxx.xxx.xxx'
2016/01/28 23:29:50 [info] 2673#0: *5 connect: app='stream' args='' flashver='WIN 20,0,0,286' swf_url='https://stream.domain.com/jwplayer-7.2.4/jwplayer.flash.swf' tc_url='rtmp://live.domain.com/stream/' page_url='https://stream.domain.com/teststream' acodecs=3575 vcodecs=252 object_encoding=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:50 [info] 2673#0: *5 createStream, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:50 [info] 2673#0: *5 play: name='teststream' args='' start=0 duration=0 reset=0 silent=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:50 [debug] 2673#0: *5 log: ngx_rtmp_log_play
2016/01/28 23:29:50 [debug] 2673#0: *5 log: ngx_rtmp_log_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 notify: ngx_rtmp_notify_play
2016/01/28 23:29:50 [debug] 2673#0: *5 notify: ngx_rtmp_notify_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 exec: ngx_rtmp_exec_play
2016/01/28 23:29:50 [debug] 2673#0: *5 exec: ngx_rtmp_exec_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 relay: ngx_rtmp_relay_play
2016/01/28 23:29:50 [info] 2673#0: *5 relay: create pull name='teststream' app='' playpath='' url='stream.domain.com:1935/stream', client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2016/01/28 23:29:50 [debug] 2673#0: *5 relay: ngx_rtmp_relay_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 play: ngx_rtmp_play_play
2016/01/28 23:29:50 [debug] 2673#0: *5 play: ngx_rtmp_play_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 live: ngx_rtmp_live_play
2016/01/28 23:29:50 [debug] 2673#0: *5 live: ngx_rtmp_live_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 access: ngx_rtmp_access_play
2016/01/28 23:29:50 [debug] 2673#0: *5 access: ngx_rtmp_access_play: next
2016/01/28 23:29:50 [debug] 2673#0: *5 cmd: ngx_rtmp_cmd_play
2016/01/28 23:31:13 [notice] 2666#0: signal 17 (SIGCHLD) received
2016/01/28 23:31:13 [alert] 2666#0: worker process 2673 exited on signal 11
2016/01/28 23:31:13 [notice] 2666#0: start worker process 2688
2016/01/28 23:31:13 [notice] 2666#0: signal 29 (SIGIO) received
```

**Comment by losywee** [comment]
Strange.

**Comment by sergey-dryabzhinsky** [comment]
Can you try to compile it with older nginx version? 1.8.x or 1.6.x

**Comment by misiek08** [comment]
You have 1024:4096 open file limit, so maybe you just try to go above
limit. Please try making this value higher (at least 16384, because you set
worker connections to 8192).

W dniu piątek, 29 stycznia 2016 Sergey <notifications@github.com>
napisał(a):

**Comment by Goz3rr** [comment]
@sergey-dryabzhinsky will try in a moment

@misiek08 isn't that what `worker_rlimit_nofile 16384;` already does?

**Comment by Goz3rr** [comment]
Alright I've tried compiling with 1.8.1 (had to remove the `--with-http_v2_module` configure flag), same thing happens, 1.6.3 doesn't compile:

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -Imodules/nginx-rtmp-module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/nginx-rtmp-module/ngx_rtmp_stat_module.o \
        modules/nginx-rtmp-module/ngx_rtmp_stat_module.c
modules/nginx-rtmp-module/ngx_rtmp_stat_module.c: In function 'ngx_rtmp_stat_init_process':
modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:119:37: error: passing argument 2 of 'ngx_event_process_posted' from incompatible pointer type [-Werror]
     ngx_event_process_posted(cycle, (ngx_queue_t*) &ngx_rtmp_init_queue);
                                     ^
In file included from src/event/ngx_event.h:561:0,
                 from src/http/ngx_http_upstream.h:14,
                 from src/http/ngx_http.h:37,
                 from modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:9:
src/event/ngx_event_posted.h:62:6: note: expected 'struct ngx_event_t **' but argument is of type 'struct ngx_queue_t *'
 void ngx_event_process_posted(ngx_cycle_t *cycle,
      ^
cc1: all warnings being treated as errors
objs/Makefile:1397: recipe for target 'objs/addon/nginx-rtmp-module/ngx_rtmp_stat_module.o' failed
make[1]: *** [objs/addon/nginx-rtmp-module/ngx_rtmp_stat_module.o] Error 1
make[1]: Leaving directory '/home/goz3rr/nginx'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by sergey-dryabzhinsky** [comment]
try to add options in ```rtmp{ server{```:
```
  chunk_size    32768;
  buflen        1s;
```

**Comment by misiek08** [comment]
This directive doesn't change system limits. You need to set another limits
in /etc/security/.... or set it before starting nginx using ulimit.

This directive changes internal nginx value and it probably won't change
your system limits (it would be security issue if application can change
that limit itself).
29 sty 2016 09:12 "Goz3rr" <notifications@github.com> napisał(a):

**Comment by Goz3rr** [comment]
@sergey-dryabzhinsky same thing happens

@misiek08 I'm not sure, but I'm on debian and have this:
```
goz3rr@faraday:~$ cat /proc/sys/fs/file-max
351887
goz3rr@faraday:~$ ulimit -Hn
65536
goz3rr@faraday:~$ ulimit -Sn
65536
```

**Comment by misiek08** [comment]
First value seems ok, the other two are for user you are logged on, not the
one used to run nginx.
29 sty 2016 15:17 "Goz3rr" <notifications@github.com> napisał(a):

**Comment by Goz3rr** [comment]
```
goz3rr@faraday:~$ sudo -u www-data -H sh -c "ulimit -Hn"
65536
goz3rr@faraday:~$ sudo -u www-data -H sh -c "ulimit -Sn"
65536
```

**Comment by misiek08** [comment]
```
2016/01/28 23:29:13 [notice] 2665#0: getrlimit(RLIMIT_NOFILE): 1024:4096
```
Maybe nginx is running on "nobody" user? You have correctly set limit for www-data and goz3rr users, but nginx still have smaller limits.

**Comment by Goz3rr** [comment]
![](http://i.imgur.com/p2VZWPe.png)

**Comment by misiek08** [comment]
How do you start nginx? init.d?

**Comment by Goz3rr** [comment]
Yes

**Comment by misiek08** [comment]
http://serverfault.com/questions/641899/ulimit-file-descriptor-limits-not-being-applied-for-particular-process

init.d apply other limits (system default ones) so please first try with *ulimit -n X* in your init.d script.

**Comment by Goz3rr** [comment]
Heh cool, never knew about that.
My log now says `2016/01/30 20:50:05 [notice] 1330#0: getrlimit(RLIMIT_NOFILE): 65535:65535` so I presume the limits changed however same problem still occurs.

**Comment by misiek08** [comment]
Ok, so you need to make core dump to see what actually is crashing workers or try with another nginx version.

**Comment by Goz3rr** [comment]
Like I said I've tried with the last stable version (1.8.1) where the same thing happens and the previous stable version (1.6.3) doesn't compile.

How would I go about making a core dump?

**Comment by misiek08** [comment]
https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/

**Comment by Goz3rr** [comment]
Does this help?

```
Core was generated by `nginx: worker pr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004fd926 in ngx_rtmp_stat_client (r=0x134fc50, lll=0x7ffeef578378, s=0x13b7d20) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:352
352         NGX_RTMP_STAT(buf, ngx_snprintf(buf, sizeof(buf), "%ui",
(gdb) backtrack full
Undefined command: "backtrack".  Try "help".
(gdb) backtrace full
#0  0x00000000004fd926 in ngx_rtmp_stat_client (r=0x134fc50, lll=0x7ffeef578378, s=0x13b7d20) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:352
        buf = "20</bw_5\240$B\001\000\000\000\000\330\v5\001"
        sa = 0x0
#1  0x00000000004fe104 in ngx_rtmp_stat_live (r=0x134fc50, lll=0x7ffeef578378, lacf=0x13bc200) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:493
        stream = 0x13c3a10
        codec = 0x0
        ctx = 0x13b8930
        rctx = 0x6d00000000000000
        recctx = 0x7ffeef578378
        s = 0x13b7d20
        n = 744
        nclients = 0
        total_nclients = 0
        rn = 206158430240
        buf = "8116", '\000' <repeats 12 times>, "\271\277;\001"
        bbuf = "@\202W\357\376\177\000\000\006\000"
        slcf = 0x1373a00
        cname = 0x142248f "</name>\r\n<live>\r\n\360$B\001"
        is_recording = 0 '\000'
#2  0x00000000004ff588 in ngx_rtmp_stat_application (r=0x134fc50, lll=0x7ffeef578378, cacf=0x13bc060) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:735
        slcf = 0x1373a00
#3  0x00000000004ff648 in ngx_rtmp_stat_server (r=0x134fc50, lll=0x7ffeef578378, cscf=0x13bb810) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:763
        cacf = 0x13bb8c8
        n = 0
#4  0x00000000004ffa85 in ngx_rtmp_stat_handler (r=0x134fc50) at modules/nginx-rtmp-module/ngx_rtmp_stat_module.c:838
        slcf = 0x1373a00
        cmcf = 0x13b4ee8
        cscf = 0x13b53a8
        cl = 0x1350b68
        l = 0x1373068
        ll = 0x1350be0
        lll = 0x7ffeef578378
        n = 0
        len = 0
        tbuf = "37", '\000' <repeats 17 times>
        nbuf = "16307", '\000' <repeats 14 times>
#5  0x00000000004545ca in ngx_http_core_content_phase (r=0x134fc50, ph=0x13b4928) at src/http/ngx_http_core_module.c:1363
        root = 20393264
        rc = 0
        path = {len = 20662544, data = 0x134fc50 "HTTP"}
#6  0x00000000004530fc in ngx_http_core_run_phases (r=0x134fc50) at src/http/ngx_http_core_module.c:840
        rc = -2
        ph = 0x13b4820
        cmcf = 0x134c7b8
#7  0x000000000045306a in ngx_http_handler (r=0x134fc50) at src/http/ngx_http_core_module.c:823
        cmcf = 0x7fdf4e3ef370
#8  0x0000000000462d95 in ngx_http_process_request (r=0x134fc50) at src/http/ngx_http_request.c:1911
        c = 0x7fdf525f37a8
#9  0x00000000004616bd in ngx_http_process_request_headers (rev=0x7fdf4e3ef370) at src/http/ngx_http_request.c:1342
        p = 0x134a880 "\360\377\377\177"
        len = 20249784
        n = 384
        rc = 0
        rv = 960
        h = 0x1350870
        c = 0x7fdf525f37a8
        hh = 0x0
        r = 0x134fc50
        cscf = 0x13709c8
        cmcf = 0x134c7b8
#10 0x0000000000460a97 in ngx_http_process_request_line (rev=0x7fdf4e3ef370) at src/http/ngx_http_request.c:1022
        n = 411
        rc = 0
        rv = 20249680
        host = {len = 20228392, data = 0x76b948 <cached_time+264> "FS\255V"}
        c = 0x7fdf525f37a8
        r = 0x134fc50
#11 0x000000000045f6f9 in ngx_http_wait_request_handler (rev=0x7fdf4e3ef370) at src/http/ngx_http_request.c:499
        p = 0x3000000020 <error: Cannot access memory at address 0x3000000020>
        size = 1024
        n = 411
        b = 0x134a940
        c = 0x7fdf525f37a8
        hc = 0x134a8e0
---Type <return> to continue, or q <return> to quit---
        cscf = 0x13709c8
#12 0x000000000044332d in ngx_epoll_process_events (cycle=0x134ac30, timer=10000, flags=1) at src/event/modules/ngx_epoll_module.c:822
        events = 1
        revents = 1
        instance = 0
        i = 0
        level = 140597067183000
        err = 0
        rev = 0x7fdf4e3ef370
        wev = 0x0
        queue = 0x76dec0 <ngx_event_timer_sentinel>
        c = 0x7fdf525f37a8
#13 0x0000000000433eab in ngx_process_events_and_timers (cycle=0x134ac30) at src/event/ngx_event.c:242
        flags = 1
        timer = 10000
        delta = 1454199622393
#14 0x0000000000440e7b in ngx_worker_process_cycle (cycle=0x134ac30, data=0x0) at src/os/unix/ngx_process_cycle.c:753
        worker = 0
#15 0x000000000043d700 in ngx_spawn_process (cycle=0x134ac30, proc=0x440d86 <ngx_worker_process_cycle>, data=0x0, name=0x522d63 "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 0
#16 0x000000000043fc6e in ngx_start_worker_processes (cycle=0x134ac30, n=1, type=-3) at src/os/unix/ngx_process_cycle.c:358
        i = 0
        ch = {command = 1, pid = 0, slot = 0, fd = 0}
#17 0x000000000043f2e7 in ngx_master_process_cycle (cycle=0x134ac30) at src/os/unix/ngx_process_cycle.c:130
        title = 0x13beaa4 "master process /usr/sbin/nginx"
        p = 0x13beac2 ""
        size = 31
        i = 1
        n = 140732913912000
        sigio = 20229192
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 140732913911824}, it_value = {tv_sec = 12, tv_usec = 18}}
        live = 0
        delay = 20229192
        ls = 0x0
        ccf = 0x134be18
#18 0x0000000000407ed0 in main (argc=1, argv=0x7ffeef578c08) at src/core/nginx.c:359
        b = 0x0
        log = 0x76b740 <ngx_log>
        i = 76
        cycle = 0x134ac30
        init_cycle = {conf_ctx = 0x0, pool = 0x134a720, log = 0x76b740 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0},
          log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, reusable_connections_queue = {prev = 0x0, next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0,
            size = 0, nalloc = 0, pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, shared_memory = {
            last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 21,
            data = 0x51e7de "/etc/nginx/nginx.conf"}, conf_param = {len = 0, data = 0x0}, conf_prefix = {len = 11, data = 0x51e7de "/etc/nginx/nginx.conf"}, prefix = {len = 17, data = 0x51e7cc "/usr/local/nginx/"}, lock_file = {len = 0,
            data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = 0x51d9c0 <__libc_csu_init>
        ccf = 0x134be18
```

**Comment by misiek08** [comment]
If I understand correctly this part:
```
sa = 0x0
```
says, that nginx have connection on port 0 (there is no such possibility, so just port wasn't set somewhere else).

@sergey-dryabzhinsky should we only check if data wasn't set or do we need to dig more and find where it wasn't set?

**Comment by sergey-dryabzhinsky** [comment]
Yeah, that's strange. I'll add check for data.
What should we output: ```-1``` or ```0``` if no data available?

**Comment by sergey-dryabzhinsky** [comment]
Zero is enough I think.

**Comment by sergey-dryabzhinsky** [comment]
Try latest master branch.

**Comment by Goz3rr** [comment]
Awesome, no longer crashes!
